title: Go-Micro
remote_theme: devexps/jekyll-theme-docs@main

baseurl: /go-micro

search_enabled: true
auto_page_title: true

sidebar:
  - label: Introduction
    children:
      - intro-overview
      - intro-design
      - intro-layout
  - label: Quick Start
    children:
      - quick-start-start
      - quick-start-usage
      - quick-start-plugins
      - quick-start-examples
