title: Go-Micro
remote_theme: devexps/jekyll-theme-docs@main

baseurl: /go-micro

search_enabled: true
auto_page_title: true

sidebar:
  - label: Introduction
    children:
      - overview
      - design
      - layout
  - label: Quick Start
    children:
      - start
      - usage
      - plugins
      - examples
